import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles1 from "../../styles/index.module.css";
import styles2 from "../../styles/animationTechnologies.module.css";
import MyTechnologies from "@/subComponents/myTechnologies";
import NavBar from "@/subComponents/navBar";
import jsLogo from "../../public/images/Logotipos/js.png";
import reactLogo from "../../public/images/Logotipos/react.png";
import nodeJs from "../../public/images/Logotipos/nodeJs.png";
import postgre from "../../public/images/Logotipos/postgreSql.png";
import htmlLogo from "../../public/images/Logotipos/html5.png";

const Technologies = ()=>{

    const [visibles, setVisibles] = useState({
        myDescription: false,
        form: false
      }); 

    return(
        <>  
            <Head>
                <title>Corbalan Augusto</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Oswald:wght@200&display=swap"/>
            </Head>
            <main className={styles1.main}>
                <NavBar visibility={{setVisibles, visibles}}/>
                <div className={styles2.container}>
                    <div className={styles2.subContainer}>
                            <div className={styles2.js}>
                                <Image
                                    className={styles2.jsLogo}
                                    src={jsLogo}
                                    alt='JS Logo'
                                    width={100}
                                />
                            </div>
                            <div className={styles2.react}>
                                <Image
                                    className={styles2.reactLogo}
                                    src={reactLogo}
                                    alt='React Logo'
                                    width={45}
                                />
                                <div className={styles2.moon}></div>
                            </div>
    {/* --------------------------------------------------------------------------------------------- */}
                            <div className={styles2.backend}>
                                <Image
                                    className={styles2.nodeJsLogo}
                                    src={nodeJs}
                                    alt='nodeJs Logo'
                                    width={100}
                                />
                                <Image
                                    className={styles2.postgreLogo}
                                    src={postgre}
                                    alt='sql Logo'
                                    width={100}
                                />
                            </div>
                            <div className={styles2.sequelize}>
                                <Image
                                    className={styles2.sequelizeLogo}
                                    src={reactLogo}
                                    alt='React Logo'
                                    width={45}
                                    />
                            {/* <div className={styles2.moon}></div> */}
                        </div>
    {/* --------------------------------------------------------------------------------------------- */}
                            {/* <div className={styles2.postgre}>
                                <Image
                                    className={styles2.postgreLogo}
                                    src={postgre}
                                    alt='sql Logo'
                                    width={100}
                                />
                            </div> */}
                            {/* <div className={styles2.earth}>
                                <Image
                                    className={styles2.React}
                                    src={reactLogo}
                                    alt='React Logo'
                                    width={45}
                                    />
                            <div className={styles2.moon}></div>
                        </div> */}
                    </div>
                    
                </div>
            </main>
            {/* <main className={styles.main}>
                <NavBar visibility={{setVisibles, visibles}}/>
                <MyTechnologies/>
            </main> */}
        </>
    )
}

export default Technologies;