import Head from 'next/head';
import { useState } from 'react';
import styles from '../../styles/index.module.css';
import NavBar from '../../subComponents/navBar';
import Form from '../../subComponents/form';
import MyProjects from '@/subComponents/myProjects';

const Portfolio =()=>{

    const [visibles, setVisibles] = useState({
        myDescription: false,
        form: false
      }); 
    return(
        <>
            <Head>
                <title>Corbalan Augusto</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Oswald:wght@200&display=swap"/>
            </Head>
            <main className={styles.main}>
                <NavBar visibility={{setVisibles, visibles}}/>
                <div className={styles.linea}/>
                <Form status={visibles.form} visibility={{setVisibles, visibles}}/>
                <div className={styles.containerOn}>
                    <MyProjects/>
                    <div className={styles.linea}/>
                </div>
            </main>
        </>
    )
}

export default Portfolio;