import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import profilePict from '../public/images/profile_picture.png';
import styles from '../styles/index.module.css';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Corbalan Augusto</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Oswald:wght@200&display=swap"/>
      </Head>
      <main className={styles.main}>
        <div className={styles.presentation}>
          <div className={styles.subcontainer1}>
            <div className={styles.image}>
              <Image
                className={styles.profilePict}
                src={profilePict} 
                alt= "Picture of the author"
                width={300}
                />
            </div>
            <div className={styles.message}>
              <h1>Corbalan Augusto N.</h1>
              <h3>__ Full Stack Developer __</h3>
            </div>
          </div>
          
        </div>
        <div className={styles.technoligies}>
          <h1>Estas son mis tecnologias</h1>
        </div>
        <h1></h1>
       
      </main>
    </>
  )
}
