import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import profilePict from '../public/images/profile_picture.png';
import reactLogo from '../public/images/Logotipos/react.png';
import reactColorLogo from '../public/images/Logotipos/reactColor.png';
import jsLogo from '../public/images/Logotipos/js.png';
import jsColorLogo from '../public/images/Logotipos/jsColor.png';
import cssLogo from '../public/images/Logotipos/css.png';
import cssColorLogo from '../public/images/Logotipos/cssColor.png';
import html5Logo from '../public/images/Logotipos/html5.png';
import html5ColorLogo from '../public/images/Logotipos/html5Color.png';
import postgreSqlLogo from '../public/images/Logotipos/postgreSql.png';
import postgreSqlColorLogo from '../public/images/Logotipos/postgreSqlColor.png';
import nodeJsLogo from '../public/images/Logotipos/nodeJs.png';
import nodeJsColorLogo from '../public/images/Logotipos/nodeJsColor.png';
import flecha from '../public/iconos/flecha_abajo.png';
import { useState } from 'react';
import styles from '../styles/index.module.css';
import ParticlesBackground from './particles/particlesBackground';
import backgroundRecipe from '../public/images/backgroundRecipes.jpg';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  
  const [visible, setVisible] = useState(false);
  const [over, setOver] = useState({
    overJs: false,
    overReact: false,
    overCss: false,
    overHtml: false,
    overPostgreSql: false,
    overNodeJs: false
  })

  const handleVisibility=()=>{
    setVisible(!visible)
  }

  return (
    <>
      <Head>
        <title>Corbalan Augusto</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Oswald:wght@200&display=swap"/>
      </Head>
      <main className={styles.main}>
        <div className={styles.container1}>
          <div className={styles.subcontainer1}>
            <ParticlesBackground className={styles.particles}/>
            <div className={styles.presentation}>
              <div className={styles.message}>
                <h1 className={styles.text_h1}>Corbalan Augusto N.</h1>
                <h3 className={styles.text_h3}>___ Full Stack Developer ___</h3>
              </div>
            </div>
          </div>
        </div>
        <div className={styles.linea}/>
        <div className={styles.subcontainer3}>
            <h3 className={styles.text_h4}>¿ Quien soy ?</h3>
            <div className={styles.subcontainer3_1}>
              <div className={styles.myPhoto}>
                <Image
                  className={styles.profilePict}
                  src={profilePict} 
                  alt= "Picture of the author"
                  width={200}
                />
              </div>
              <div className={styles.myDescription1}>
                <p className={styles.text_p}>
                  Hola, mi nombre es Augusto Corbalán, soy de Alta Gracia - Córdoba, Argentina.<br/>

                  <br/>Soy Full Stack web Developer, cuento con 800 horas de programación realizadas en el bootcamp 
                  "Soy Henry" tanto en tareas y proyectos individuales como grupales. Estando capacitado para trabajar 
                  con las tecnologías de JavaScript, React.js, Redux.js, Node.js, PostgreSQL, Sequelize.js, HTML, CSS, entre otras. 
                  Tanto de forma individual como en equipo con la tecnología GIT.<br/>
                </p>
              </div>
            </div>
            <div className={ visible ? styles.noVisible : styles.desplegator} onClick={()=>handleVisibility()}>
              <Image
                src={flecha}
                alt= "flecha hacia abajo"
                width={45}
              />
            </div>
            <div>
              <div className={visible ? styles.myDescription2Visible : styles.noVisible }>
                <p className={styles.text_p}>
                  <br/>- ¿Cómo llegué a Full Stack Developer?<br/>

                  <br/>Inicié mi carrera como Desarrollador luego de descubrir en la carrera de Ingeniería la importancia de la programación 
                  para la resolución de los problemas y búsqueda de las soluciones más eficientes para los problemas de la actualidad.<br/>

                  Desde chico tuve un gran interés y habilidad para la resolución de problemas relacionados con tecnología, es por ello 
                  que siempre dediqué mi tiempo y esfuerzo a buscar las herramientas que me permitan encontrar las soluciones más eficientes a estos.<br/>

                  <br/>- ¿Por qué desarrollo WEB?<br/>

                  <br/>Decidí comenzar en desarrollo web ya que considero que es la mejor forma de iniciar en el mundo de la programación y desarrollo de soluciones 
                  por medio de software. 
                  Actualmente sigo estudiando y capacitándome para profundizar cada vez más mis conocimientos en el desarrollo de software web, mejorar mi capacidad 
                  de razonamiento lógico, algoritmia, y conocimiento de nuevas tecnologías. 
                  Buscando de esta forma poder lograr soluciones cada vez mejores y más eficientes a los problemas que se presentan. 
                </p>
                <div className={ visible ? styles.desplegator: styles.noVisible } onClick={()=>handleVisibility()}>
                    <Image
                      src={flecha}
                      alt= "flecha hacia arriba"
                      width={45}
                      className={styles.iconFlechaArriba}
                    />
                </div>
              </div>
            </div>
          </div>
          <div className={styles.linea}/>
          <div className={styles.subcontainer2}>
            <h3 className={styles.text_h3}>Tecnologías</h3>
            <div className={styles.logotypes}>
              <Image
                className={styles.JavaScript}
                src={over.overJs? jsColorLogo : jsLogo}
                alt='JS Logo'
                width={120}
                onMouseOver={()=>setOver({...over, overJs: true})}
                onMouseOut={()=>setOver({...over, overJs: false})}
              />
              <Image
                className={styles.React}
                src={over.overReact? reactColorLogo : reactLogo}
                alt='React Logo'
                width={150}
                onMouseOver={()=>setOver({...over, overReact: true})}
                onMouseOut={()=>setOver({...over, overReact: false})}
              />
              <Image
                className={styles.Css}
                src={over.overCss? cssColorLogo : cssLogo}
                alt='Css Logo'
                width={120}
                onMouseOver={()=>setOver({...over, overCss: true})}
                onMouseOut={()=>setOver({...over, overCss: false})}
              />
              <Image
                className={styles.html5}
                src={over.overHtml? html5ColorLogo : html5Logo}
                alt='Html5 Logo'
                width={120}
                onMouseOver={()=>setOver({...over, overHtml: true})}
                onMouseOut={()=>setOver({...over, overHtml: false})}
              />
              <Image
                className={styles.postgreSql}
                src={over.overPostgreSql? postgreSqlColorLogo : postgreSqlLogo}
                alt='postgreSql Logo'
                width={120}
                onMouseOver={()=>setOver({...over, overPostgreSql: true})}
                onMouseOut={()=>setOver({...over, overPostgreSql: false})}
              />
              <Image
                className={styles.nodeJs}
                src={over.overNodeJs? nodeJsColorLogo : nodeJsLogo}
                alt='nodeJs Logo'
                width={120}
                onMouseOver={()=>setOver({...over, overNodeJs: true})}
                onMouseOut={()=>setOver({...over, overNodeJs: false})}
              />
            </div>
          </div>
          <div className={styles.linea}/>
          <div className={styles.subcontainer4}>

            <h3 className={styles.text_h3}>Mis proyectos</h3>

            <div className={styles.containerProject}>
              <div className={styles.project}>
                <div className={styles.nameProject}>
                  <h4 className={styles.text_h4}>PI-FOOD</h4>
                  <p className={styles.text_pmin}>  by AUGUSTO CORBALAN</p>
                </div>
                <div className={styles.descriptionProject}>
                  <p className={styles.text_p}>Descripción:</p>
                  <p className={styles.text_pmin}>
                    "RecipesHenry" es una aplicación en la cual se pueden ver distintas recetas de comida 
                    junto con información relevante de las mismas utilizando la api externa "spoonacular" 
                    y a partir de ella poder, entre otras cosas: Buscar, Filtrar y Ordenar resultados y Crear nuevas recetas
                  </p>
                  <p className={styles.text_p}>Tecnologías:</p>
                  <p className={styles.text_pmin}>
                    React | Redux | nodeJs | Sequelize | PostgreSQL
                  </p>
                </div>
              </div>
            </div>

          </div>
        <h1></h1>
       
      </main>
    </>
  )
}
